name: build

on:
  create:
    tags:
     - '*'

jobs:
  build:
    name: Building on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
         - os: ubuntu-latest
           prometheus_artifact_name: prometheus
           prometheus_asset_name: prometheus-linux-amd64
         - os: windows-latest
           prometheus_artifact_name: prometheus.exe
           prometheus_asset_name: prometheus-windows-amd64.exe
         - os: macos-latest
           prometheus_artifact_name: prometheus
           prometheus_asset_name: prometheus-macos-amd64
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Make the build dir
      run: mkdir "${{ runner.workspace }}/build"
      
    - name: Build UI Assets
      run: make assets
      
    - name: Build
      run: go build -o ${{ runner.workspace }}/build/${{ matrix.prometheus_artifact_name }} ./cmd/prometheus/main.go
      
    - name: make dir to tar
      run: mkdir ${{ matrix.prometheus_asset_name }}
      
    - name: move binary
      run: cp ${{ runner.workspace }}/build/${{ matrix.prometheus_artifact_name }} ${{ matrix.prometheus_asset_name }}/.
      
    - name: copy web
      run: cp -r ./web/ui/. ${{ matrix.prometheus_asset_name }}/.
    
    - name: tar
      run: tar -zcvf ${{ matrix.prometheus_asset_name }}.tar.gz ${{ matrix.prometheus_asset_name }}
      
    - name: Upload prometheus binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.prometheus_asset_name }}.tar.gz
        asset_name: ${{ matrix.prometheus_asset_name }}.tar.gz
        tag: ${{ github.ref }}
